name = "ProximalAlgorithms"
uuid = "140ffc9f-1907-541a-a177-7475e0a401e9"
version = "0.8.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OperatorCore = "3945cd23-d97e-4db0-9df2-35342dbd287d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProximalCore = "dc4f5ac2-75d1-4f31-931e-60435d74994b"

[compat]
ADTypes = "1.5.3"
AbstractOperators = "0.4"
Aqua = "0.8"
DifferentiationInterface = "0.6.2"
ForwardDiff = "0.10"
LinearAlgebra = "1.2"
OperatorCore = "0.1"
Printf = "1.2"
ProximalCore = "0.2"
ProximalOperators = "0.17"
Random = "1"
RecursiveArrayTools = "3.31"
ReverseDiff = "1.15"
Test = "1.11"
Zygote = "0.7"
julia = "1.6"

[extras]
AbstractOperators = "d9c5613a-d543-52d8-9afd-8f241a8c3f1c"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["AbstractOperators", "Aqua", "ForwardDiff", "ProximalOperators", "Random", "RecursiveArrayTools", "ReverseDiff", "Test", "Zygote"]
